export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_FETCHED = 'USER_FETCHED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const NOTE_CREATED = 'NOTE_CREATED';
export const NOTES_FETCHED = 'NOTES_FETCHED';
